type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$", ".bz2$", ".xz$"]
multiline:
  pattern: "^\\s"
  match: after
{{ if .convert_timezone }}
processors:
- add_locale: ~
{{ end }}
